### ISSUE TITLE
Can you provide an example with partials ?

### ISSUE THREAD

**Issue by SiegfriedEhret** [MakeNowJust/crustache#23]
Hello !

Thanks for your lib, it's great.
I have an issue working with partials.

I have:
- `index.html` which contains `<div class="header1">{{>header}}</div>`.
- `header.html` which contains `<h1>{{header}}</h1>`.

Here is my small program:

```crystal
require "crustache"

cwd = Dir.current
path = Path[cwd]
indexPath = path.join("index.html")
index = Crustache.parse File.read(indexPath)
model = {
  "header" => "Hello, world!",
}
html = Crustache.render(index, model)
puts html
```

The result is `<div class="header1"></div>`, it should be `<div class="header1">Hello, world!</div>`

I think I am not loading the templates correctly but I am not sure.

 お願いします !

**Comment by makenowjust** [comment]
You should use `Crustache.loader` for getting `fs` and should pass this `fs` to `render`:

```crystal
require "crustache"

fs = Crustache.loader Dir.current
index = fs.load! "index"
model = {
  "header" => "Hello, world!",
}
html = Crustache.render(index, model, fs)
puts html
```

**Comment by SiegfriedEhret** [comment]
Awesome ! Thanks !
