### ISSUE TITLE
How to use lambdas ?

### ISSUE THREAD

**Issue by SiegfriedEhret** [MakeNowJust/crustache#24]
Hello, it's me again !

From [Mustache documentation](https://mustache.github.io/mustache.5.html), a value can be "a callable object".

My idea is to implement shortcodes, like in [hugo](https://gohugo.io/content-management/shortcodes/#youtube), either as:
- a fake partial `{{> youtube abc123}}` which expands to a youtube iframe to include.
- a block as described in the mustache spec.

I am trying to extend this example from your tests:

```crystal
fs = Crustache::HashFileSystem.new
fs.register "test", Crustache.parse "Test {{.}}"
engine = Crustache::Engine.new fs
output = IO::Memory.new
engine.render("test", "Test", output)
output.to_s.should eq("Test Test")
```

I can't get this to work.

Do you think it is possible ?

**Comment by makenowjust** [comment]
Your example works without any problems on my computer, and it seems this example is not related to lambdas. What do you mean?

Code:

```crystal
require "spec"

require "./src/crustache"

fs = Crustache::HashFileSystem.new
fs.register "test", Crustache.parse "Test {{.}}"

engine = Crustache::Engine.new fs

output = IO::Memory.new
engine.render("test", "Test", output)

it do
  output.to_s.should eq("Test Test")
end
```

Result:

![スクリーンショット 2019-05-19 13 45 04](https://user-images.githubusercontent.com/6679325/57977880-7d47e180-7a3c-11e9-97be-35f2df8131dd.png)

**Comment by makenowjust** [comment]
Is this you want?

```crystal
require "./src/crustache"

class YoutubeFS < Crustache::HashFileSystem
  def load(name)
    if /\Ayoutube\s+(\w+)\z/ === name
      id = $1
      html = <<-HTML
        <iframe
          type="text/html"
          width="640" height="360"
          src="http://www.youtube.com/embed/#{id}"
          frameborder="0"
          />
        HTML

      return Crustache.parse html
    end

    super
  end
end

fs = YoutubeFS.new
fs.register "test", Crustache.parse <<-HTML
  {{> youtube abc123}}
  HTML

engine = Crustache::Engine.new fs

output = IO::Memory.new
engine.render("test", nil, output)

pp output.to_s
```

```console
$ crystal run ytfs.cr
"<iframe\n" +
"  type=\"text/html\"\n" +
"  width=\"640\" height=\"360\"\n" +
"  src=\"http://www.youtube.com/embed/abc123\"\n" +
"  frameborder=\"0\"\n" +
"  />"
```

**Comment by SiegfriedEhret** [comment]
Awesome !!
Yeah that's exactly what I was looking for.
I tried to hack my way into the code for partials but could not get something nice.
Thank you very much !
