### ISSUE TITLE
Error: def write_byte must return Int64 but it is returning (Int64 | Nil)

### ISSUE THREAD

**Issue by Blacksmoke16** [MakeNowJust/crustache#27]
https://github.com/MakeNowJust/crustache/blob/master/src/crustache/indent_io.cr#L23-L40 will need to be updated to return the amount of written bytes as per https://github.com/crystal-lang/crystal/pull/9233 for `0.35.0`.

EDIT: Prob should setup periodic CI against nightly, would have caught this sooner.

**Comment by makenowjust** [comment]
@Blacksmoke16 Thanks for report!
