### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by waghanza** [MakeNowJust/crustache#28]
Hi @MakeNowJust,

Thanks for `crustache` and the update to `crystal` **0.35**

However, I notice that tag `2.4.2` contains an incorrect version number in https://github.com/MakeNowJust/crustache/blob/ca2902b019615a0046a5cbddb850ff81eedba3c6/shard.yml#L2

Regards,

**Comment by makenowjust** [comment]
It's my mistake. Thanks.
